<?php
/*
 * APIMATICCalculatorLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/02/2016
 */

namespace APIMATICCalculatorLib\Models;

/**
 * The operator to apply on the variables
 */
class OperationEnum {
    /**
     * TODO: Write general description for this element
     */
    const SUM = "SUM";

    /**
     * TODO: Write general description for this element
     */
    const SUBTRACT = "SUBTRACT";

    /**
     * TODO: Write general description for this element
     */
    const MULTIPLY = "MULTIPLY";

    /**
     * TODO: Write general description for this element
     */
    const DIVIDE = "DIVIDE";

}