<?php
/*
 * APIMATICCalculatorLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/02/2016
 */

namespace APIMATICCalculatorLib;

use APIMATICCalculatorLib\Controllers;

/**
 * APIMATICCalculatorLib client class
 */
class APIMATICCalculatorClient
{
 
    /**
     * Singleton access to Operation controller
     * @return Controllers\OperationController The *Singleton* instance
     */
    public function getOperation()
    {
        return Controllers\OperationController::getInstance();
    }
}